services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    env_file:
      - .env
    command: ./api
    restart: unless-stopped
    networks:
      - internal

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ./migrate
    networks:
      - internal

  caddy:
    image: caddy:2
    ports:
      - "3000:3000" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - internal
    depends_on:
      - api
    restart: unless-stopped

networks:
  internal:
    driver: bridge